# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/Development/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/Development/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/Workspace/crypto/arbitrage/blackbird

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/Workspace/crypto/arbitrage/blackbird

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/Development/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/Development/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Workspace/crypto/arbitrage/blackbird/CMakeFiles /Volumes/Workspace/crypto/arbitrage/blackbird/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Workspace/crypto/arbitrage/blackbird/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named all_pch

# Build rule for target.
all_pch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_pch
.PHONY : all_pch

# fast build rule for target.
all_pch/fast:
	$(MAKE) -f CMakeFiles/all_pch.dir/build.make CMakeFiles/all_pch.dir/build
.PHONY : all_pch/fast

#=============================================================================
# Target rules for targets named blackbird_pch

# Build rule for target.
blackbird_pch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackbird_pch
.PHONY : blackbird_pch

# fast build rule for target.
blackbird_pch/fast:
	$(MAKE) -f CMakeFiles/blackbird_pch.dir/build.make CMakeFiles/blackbird_pch.dir/build
.PHONY : blackbird_pch/fast

#=============================================================================
# Target rules for targets named clean_cotire

# Build rule for target.
clean_cotire: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_cotire
.PHONY : clean_cotire

# fast build rule for target.
clean_cotire/fast:
	$(MAKE) -f CMakeFiles/clean_cotire.dir/build.make CMakeFiles/clean_cotire.dir/build
.PHONY : clean_cotire/fast

#=============================================================================
# Target rules for targets named all_unity

# Build rule for target.
all_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_unity
.PHONY : all_unity

# fast build rule for target.
all_unity/fast:
	$(MAKE) -f CMakeFiles/all_unity.dir/build.make CMakeFiles/all_unity.dir/build
.PHONY : all_unity/fast

#=============================================================================
# Target rules for targets named blackbird_unity

# Build rule for target.
blackbird_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackbird_unity
.PHONY : blackbird_unity

# fast build rule for target.
blackbird_unity/fast:
	$(MAKE) -f CMakeFiles/blackbird_unity.dir/build.make CMakeFiles/blackbird_unity.dir/build
.PHONY : blackbird_unity/fast

#=============================================================================
# Target rules for targets named blackbird

# Build rule for target.
blackbird: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackbird
.PHONY : blackbird

# fast build rule for target.
blackbird/fast:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/build
.PHONY : blackbird/fast

cotire/blackbird_CXX_unity.o: cotire/blackbird_CXX_unity.cxx.o

.PHONY : cotire/blackbird_CXX_unity.o

# target to build an object file
cotire/blackbird_CXX_unity.cxx.o:
	$(MAKE) -f CMakeFiles/blackbird_unity.dir/build.make CMakeFiles/blackbird_unity.dir/cotire/blackbird_CXX_unity.cxx.o
.PHONY : cotire/blackbird_CXX_unity.cxx.o

cotire/blackbird_CXX_unity.i: cotire/blackbird_CXX_unity.cxx.i

.PHONY : cotire/blackbird_CXX_unity.i

# target to preprocess a source file
cotire/blackbird_CXX_unity.cxx.i:
	$(MAKE) -f CMakeFiles/blackbird_unity.dir/build.make CMakeFiles/blackbird_unity.dir/cotire/blackbird_CXX_unity.cxx.i
.PHONY : cotire/blackbird_CXX_unity.cxx.i

cotire/blackbird_CXX_unity.s: cotire/blackbird_CXX_unity.cxx.s

.PHONY : cotire/blackbird_CXX_unity.s

# target to generate assembly for a file
cotire/blackbird_CXX_unity.cxx.s:
	$(MAKE) -f CMakeFiles/blackbird_unity.dir/build.make CMakeFiles/blackbird_unity.dir/cotire/blackbird_CXX_unity.cxx.s
.PHONY : cotire/blackbird_CXX_unity.cxx.s

src/components/check_entry_exit.o: src/components/check_entry_exit.cpp.o

.PHONY : src/components/check_entry_exit.o

# target to build an object file
src/components/check_entry_exit.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/check_entry_exit.cpp.o
.PHONY : src/components/check_entry_exit.cpp.o

src/components/check_entry_exit.i: src/components/check_entry_exit.cpp.i

.PHONY : src/components/check_entry_exit.i

# target to preprocess a source file
src/components/check_entry_exit.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/check_entry_exit.cpp.i
.PHONY : src/components/check_entry_exit.cpp.i

src/components/check_entry_exit.s: src/components/check_entry_exit.cpp.s

.PHONY : src/components/check_entry_exit.s

# target to generate assembly for a file
src/components/check_entry_exit.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/check_entry_exit.cpp.s
.PHONY : src/components/check_entry_exit.cpp.s

src/components/parameters.o: src/components/parameters.cpp.o

.PHONY : src/components/parameters.o

# target to build an object file
src/components/parameters.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/parameters.cpp.o
.PHONY : src/components/parameters.cpp.o

src/components/parameters.i: src/components/parameters.cpp.i

.PHONY : src/components/parameters.i

# target to preprocess a source file
src/components/parameters.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/parameters.cpp.i
.PHONY : src/components/parameters.cpp.i

src/components/parameters.s: src/components/parameters.cpp.s

.PHONY : src/components/parameters.s

# target to generate assembly for a file
src/components/parameters.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/parameters.cpp.s
.PHONY : src/components/parameters.cpp.s

src/components/result.o: src/components/result.cpp.o

.PHONY : src/components/result.o

# target to build an object file
src/components/result.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/result.cpp.o
.PHONY : src/components/result.cpp.o

src/components/result.i: src/components/result.cpp.i

.PHONY : src/components/result.i

# target to preprocess a source file
src/components/result.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/result.cpp.i
.PHONY : src/components/result.cpp.i

src/components/result.s: src/components/result.cpp.s

.PHONY : src/components/result.s

# target to generate assembly for a file
src/components/result.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/result.cpp.s
.PHONY : src/components/result.cpp.s

src/components/symbol.o: src/components/symbol.cpp.o

.PHONY : src/components/symbol.o

# target to build an object file
src/components/symbol.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/symbol.cpp.o
.PHONY : src/components/symbol.cpp.o

src/components/symbol.i: src/components/symbol.cpp.i

.PHONY : src/components/symbol.i

# target to preprocess a source file
src/components/symbol.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/symbol.cpp.i
.PHONY : src/components/symbol.cpp.i

src/components/symbol.s: src/components/symbol.cpp.s

.PHONY : src/components/symbol.s

# target to generate assembly for a file
src/components/symbol.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/components/symbol.cpp.s
.PHONY : src/components/symbol.cpp.s

src/exchanges/abstracts/AbstractExchange.o: src/exchanges/abstracts/AbstractExchange.cpp.o

.PHONY : src/exchanges/abstracts/AbstractExchange.o

# target to build an object file
src/exchanges/abstracts/AbstractExchange.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/abstracts/AbstractExchange.cpp.o
.PHONY : src/exchanges/abstracts/AbstractExchange.cpp.o

src/exchanges/abstracts/AbstractExchange.i: src/exchanges/abstracts/AbstractExchange.cpp.i

.PHONY : src/exchanges/abstracts/AbstractExchange.i

# target to preprocess a source file
src/exchanges/abstracts/AbstractExchange.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/abstracts/AbstractExchange.cpp.i
.PHONY : src/exchanges/abstracts/AbstractExchange.cpp.i

src/exchanges/abstracts/AbstractExchange.s: src/exchanges/abstracts/AbstractExchange.cpp.s

.PHONY : src/exchanges/abstracts/AbstractExchange.s

# target to generate assembly for a file
src/exchanges/abstracts/AbstractExchange.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/abstracts/AbstractExchange.cpp.s
.PHONY : src/exchanges/abstracts/AbstractExchange.cpp.s

src/exchanges/bitfinex.o: src/exchanges/bitfinex.cpp.o

.PHONY : src/exchanges/bitfinex.o

# target to build an object file
src/exchanges/bitfinex.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/bitfinex.cpp.o
.PHONY : src/exchanges/bitfinex.cpp.o

src/exchanges/bitfinex.i: src/exchanges/bitfinex.cpp.i

.PHONY : src/exchanges/bitfinex.i

# target to preprocess a source file
src/exchanges/bitfinex.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/bitfinex.cpp.i
.PHONY : src/exchanges/bitfinex.cpp.i

src/exchanges/bitfinex.s: src/exchanges/bitfinex.cpp.s

.PHONY : src/exchanges/bitfinex.s

# target to generate assembly for a file
src/exchanges/bitfinex.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/bitfinex.cpp.s
.PHONY : src/exchanges/bitfinex.cpp.s

src/exchanges/bitstamp.o: src/exchanges/bitstamp.cpp.o

.PHONY : src/exchanges/bitstamp.o

# target to build an object file
src/exchanges/bitstamp.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/bitstamp.cpp.o
.PHONY : src/exchanges/bitstamp.cpp.o

src/exchanges/bitstamp.i: src/exchanges/bitstamp.cpp.i

.PHONY : src/exchanges/bitstamp.i

# target to preprocess a source file
src/exchanges/bitstamp.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/bitstamp.cpp.i
.PHONY : src/exchanges/bitstamp.cpp.i

src/exchanges/bitstamp.s: src/exchanges/bitstamp.cpp.s

.PHONY : src/exchanges/bitstamp.s

# target to generate assembly for a file
src/exchanges/bitstamp.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/bitstamp.cpp.s
.PHONY : src/exchanges/bitstamp.cpp.s

src/exchanges/btce.o: src/exchanges/btce.cpp.o

.PHONY : src/exchanges/btce.o

# target to build an object file
src/exchanges/btce.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/btce.cpp.o
.PHONY : src/exchanges/btce.cpp.o

src/exchanges/btce.i: src/exchanges/btce.cpp.i

.PHONY : src/exchanges/btce.i

# target to preprocess a source file
src/exchanges/btce.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/btce.cpp.i
.PHONY : src/exchanges/btce.cpp.i

src/exchanges/btce.s: src/exchanges/btce.cpp.s

.PHONY : src/exchanges/btce.s

# target to generate assembly for a file
src/exchanges/btce.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/btce.cpp.s
.PHONY : src/exchanges/btce.cpp.s

src/exchanges/components/ExchangeParameters.o: src/exchanges/components/ExchangeParameters.cpp.o

.PHONY : src/exchanges/components/ExchangeParameters.o

# target to build an object file
src/exchanges/components/ExchangeParameters.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/components/ExchangeParameters.cpp.o
.PHONY : src/exchanges/components/ExchangeParameters.cpp.o

src/exchanges/components/ExchangeParameters.i: src/exchanges/components/ExchangeParameters.cpp.i

.PHONY : src/exchanges/components/ExchangeParameters.i

# target to preprocess a source file
src/exchanges/components/ExchangeParameters.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/components/ExchangeParameters.cpp.i
.PHONY : src/exchanges/components/ExchangeParameters.cpp.i

src/exchanges/components/ExchangeParameters.s: src/exchanges/components/ExchangeParameters.cpp.s

.PHONY : src/exchanges/components/ExchangeParameters.s

# target to generate assembly for a file
src/exchanges/components/ExchangeParameters.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchanges/components/ExchangeParameters.cpp.s
.PHONY : src/exchanges/components/ExchangeParameters.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/base64.o: src/utils/base64.cpp.o

.PHONY : src/utils/base64.o

# target to build an object file
src/utils/base64.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/base64.cpp.o
.PHONY : src/utils/base64.cpp.o

src/utils/base64.i: src/utils/base64.cpp.i

.PHONY : src/utils/base64.i

# target to preprocess a source file
src/utils/base64.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/base64.cpp.i
.PHONY : src/utils/base64.cpp.i

src/utils/base64.s: src/utils/base64.cpp.s

.PHONY : src/utils/base64.s

# target to generate assembly for a file
src/utils/base64.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/base64.cpp.s
.PHONY : src/utils/base64.cpp.s

src/utils/curl_fun.o: src/utils/curl_fun.cpp.o

.PHONY : src/utils/curl_fun.o

# target to build an object file
src/utils/curl_fun.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/curl_fun.cpp.o
.PHONY : src/utils/curl_fun.cpp.o

src/utils/curl_fun.i: src/utils/curl_fun.cpp.i

.PHONY : src/utils/curl_fun.i

# target to preprocess a source file
src/utils/curl_fun.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/curl_fun.cpp.i
.PHONY : src/utils/curl_fun.cpp.i

src/utils/curl_fun.s: src/utils/curl_fun.cpp.s

.PHONY : src/utils/curl_fun.s

# target to generate assembly for a file
src/utils/curl_fun.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/curl_fun.cpp.s
.PHONY : src/utils/curl_fun.cpp.s

src/utils/db_fun.o: src/utils/db_fun.cpp.o

.PHONY : src/utils/db_fun.o

# target to build an object file
src/utils/db_fun.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/db_fun.cpp.o
.PHONY : src/utils/db_fun.cpp.o

src/utils/db_fun.i: src/utils/db_fun.cpp.i

.PHONY : src/utils/db_fun.i

# target to preprocess a source file
src/utils/db_fun.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/db_fun.cpp.i
.PHONY : src/utils/db_fun.cpp.i

src/utils/db_fun.s: src/utils/db_fun.cpp.s

.PHONY : src/utils/db_fun.s

# target to generate assembly for a file
src/utils/db_fun.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/db_fun.cpp.s
.PHONY : src/utils/db_fun.cpp.s

src/utils/restapi.o: src/utils/restapi.cpp.o

.PHONY : src/utils/restapi.o

# target to build an object file
src/utils/restapi.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/restapi.cpp.o
.PHONY : src/utils/restapi.cpp.o

src/utils/restapi.i: src/utils/restapi.cpp.i

.PHONY : src/utils/restapi.i

# target to preprocess a source file
src/utils/restapi.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/restapi.cpp.i
.PHONY : src/utils/restapi.cpp.i

src/utils/restapi.s: src/utils/restapi.cpp.s

.PHONY : src/utils/restapi.s

# target to generate assembly for a file
src/utils/restapi.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/restapi.cpp.s
.PHONY : src/utils/restapi.cpp.s

src/utils/send_email.o: src/utils/send_email.cpp.o

.PHONY : src/utils/send_email.o

# target to build an object file
src/utils/send_email.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/send_email.cpp.o
.PHONY : src/utils/send_email.cpp.o

src/utils/send_email.i: src/utils/send_email.cpp.i

.PHONY : src/utils/send_email.i

# target to preprocess a source file
src/utils/send_email.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/send_email.cpp.i
.PHONY : src/utils/send_email.cpp.i

src/utils/send_email.s: src/utils/send_email.cpp.s

.PHONY : src/utils/send_email.s

# target to generate assembly for a file
src/utils/send_email.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/send_email.cpp.s
.PHONY : src/utils/send_email.cpp.s

src/utils/time_fun.o: src/utils/time_fun.cpp.o

.PHONY : src/utils/time_fun.o

# target to build an object file
src/utils/time_fun.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/time_fun.cpp.o
.PHONY : src/utils/time_fun.cpp.o

src/utils/time_fun.i: src/utils/time_fun.cpp.i

.PHONY : src/utils/time_fun.i

# target to preprocess a source file
src/utils/time_fun.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/time_fun.cpp.i
.PHONY : src/utils/time_fun.cpp.i

src/utils/time_fun.s: src/utils/time_fun.cpp.s

.PHONY : src/utils/time_fun.s

# target to generate assembly for a file
src/utils/time_fun.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/time_fun.cpp.s
.PHONY : src/utils/time_fun.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... all_pch"
	@echo "... blackbird_pch"
	@echo "... clean_cotire"
	@echo "... all_unity"
	@echo "... blackbird_unity"
	@echo "... blackbird"
	@echo "... cotire/blackbird_CXX_unity.o"
	@echo "... cotire/blackbird_CXX_unity.i"
	@echo "... cotire/blackbird_CXX_unity.s"
	@echo "... src/components/check_entry_exit.o"
	@echo "... src/components/check_entry_exit.i"
	@echo "... src/components/check_entry_exit.s"
	@echo "... src/components/parameters.o"
	@echo "... src/components/parameters.i"
	@echo "... src/components/parameters.s"
	@echo "... src/components/result.o"
	@echo "... src/components/result.i"
	@echo "... src/components/result.s"
	@echo "... src/components/symbol.o"
	@echo "... src/components/symbol.i"
	@echo "... src/components/symbol.s"
	@echo "... src/exchanges/abstracts/AbstractExchange.o"
	@echo "... src/exchanges/abstracts/AbstractExchange.i"
	@echo "... src/exchanges/abstracts/AbstractExchange.s"
	@echo "... src/exchanges/bitfinex.o"
	@echo "... src/exchanges/bitfinex.i"
	@echo "... src/exchanges/bitfinex.s"
	@echo "... src/exchanges/bitstamp.o"
	@echo "... src/exchanges/bitstamp.i"
	@echo "... src/exchanges/bitstamp.s"
	@echo "... src/exchanges/btce.o"
	@echo "... src/exchanges/btce.i"
	@echo "... src/exchanges/btce.s"
	@echo "... src/exchanges/components/ExchangeParameters.o"
	@echo "... src/exchanges/components/ExchangeParameters.i"
	@echo "... src/exchanges/components/ExchangeParameters.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/base64.o"
	@echo "... src/utils/base64.i"
	@echo "... src/utils/base64.s"
	@echo "... src/utils/curl_fun.o"
	@echo "... src/utils/curl_fun.i"
	@echo "... src/utils/curl_fun.s"
	@echo "... src/utils/db_fun.o"
	@echo "... src/utils/db_fun.i"
	@echo "... src/utils/db_fun.s"
	@echo "... src/utils/restapi.o"
	@echo "... src/utils/restapi.i"
	@echo "... src/utils/restapi.s"
	@echo "... src/utils/send_email.o"
	@echo "... src/utils/send_email.i"
	@echo "... src/utils/send_email.s"
	@echo "... src/utils/time_fun.o"
	@echo "... src/utils/time_fun.i"
	@echo "... src/utils/time_fun.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

